### ISSUE TITLE
Exceptions in Error tab

### ISSUE THREAD

**Issue by floyd-fuh** [wallarm/jwt-heartbreaker#2]
```
java.lang.IllegalArgumentException: The RSAKey cannot be null
	at com.auth0.jwt.algorithms.RSAAlgorithm.<init>(RSAAlgorithm.java:19)
	at com.auth0.jwt.algorithms.RSAAlgorithm.<init>(RSAAlgorithm.java:26)
	at com.auth0.jwt.algorithms.Algorithm.RSA256(Algorithm.java:26)
	at pingvin.tokenposition.algorithm.AlgorithmLinker.getAlgorithm(AlgorithmLinker.java:127)
	at pingvin.tokenposition.algorithm.AlgorithmLinker.getVerifierAlgorithm(AlgorithmLinker.java:99)
	at pingvin.JwtScannerCheck.lal2(JwtScannerCheck.java:73)
	at pingvin.JwtScannerCheck.doPassiveScan(JwtScannerCheck.java:40)
	at burp.gj2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalArgumentException: The RSAKey cannot be null
	at com.auth0.jwt.algorithms.RSAAlgorithm.<init>(RSAAlgorithm.java:19)
	at com.auth0.jwt.algorithms.RSAAlgorithm.<init>(RSAAlgorithm.java:26)
	at com.auth0.jwt.algorithms.Algorithm.RSA256(Algorithm.java:26)
	at pingvin.tokenposition.algorithm.AlgorithmLinker.getAlgorithm(AlgorithmLinker.java:127)
	at pingvin.tokenposition.algorithm.AlgorithmLinker.getVerifierAlgorithm(AlgorithmLinker.java:99)
	at pingvin.JwtScannerCheck.lal2(JwtScannerCheck.java:73)
	at pingvin.JwtScannerCheck.doPassiveScan(JwtScannerCheck.java:40)
	at burp.gj2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalArgumentException: The RSAKey cannot be null
	at com.auth0.jwt.algorithms.RSAAlgorithm.<init>(RSAAlgorithm.java:19)
	at com.auth0.jwt.algorithms.RSAAlgorithm.<init>(RSAAlgorithm.java:26)
	at com.auth0.jwt.algorithms.Algorithm.RSA256(Algorithm.java:26)
	at pingvin.tokenposition.algorithm.AlgorithmLinker.getAlgorithm(AlgorithmLinker.java:127)
	at pingvin.tokenposition.algorithm.AlgorithmLinker.getVerifierAlgorithm(AlgorithmLinker.java:99)
	at pingvin.JwtScannerCheck.lal2(JwtScannerCheck.java:73)
	at pingvin.JwtScannerCheck.doPassiveScan(JwtScannerCheck.java:40)
	at burp.gj2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by jaysharma786** [comment]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.fna.a(Unknown Source)
	at burp.fna.<init>(Unknown Source)
	at burp.fm9.a(Unknown Source)
	at burp.fl5.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
